apiVersion: gate.sh/v1alpha1
kind: Gate
metadata:
  labels:
    app.kubernetes.io/name: gate-operator
    app.kubernetes.io/managed-by: kustomize
  name: gate-sample-1
spec:
  requeueAfter: 60s
  targets:
    - name: CoreDns
      selector:
        apiVersion: apps/v1
        kind: Deployment
        name: coredns
        namespace: kube-system
      validators:
        - atLeast: 1