apiVersion: gate.sh/v1alpha1
kind: Gate
metadata:
  labels:
    app.kubernetes.io/name: gate-operator
    app.kubernetes.io/managed-by: kustomize
  name: gate-sample-3
spec:
  requeueAfter: 60s
  targets:
    - name: WeirdConditionType
      selector:
        apiVersion: apps/v1
        kind: Deployment
        namespace: kube-system
        name: coredns
      validators:
        - matchCondition:
            type: "Weirdo"
            status: "True"