name: bump-version

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New version (e.g. 1.2.3 or 1.2.3-rc1)'
        required: true
        type: string

permissions:
  contents: write  # for creating PRs and pushing changes
  pull-requests: write  # for opening PRs

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    if: |
      ${{github.repository == 'robinlioret/gate-operator' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v5.1.0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump versions in docs
        run: |
          chmod +x hack/bump-version.sh
          ./hack/bump-version.sh ${{ github.event.inputs.new_version }}
          git add .

      - name: Bump versions in build installer
        run: |
          make build-installer IMG=ghcr.io/robinlioret/gate-operator:v${{ github.event.inputs.new_version }}
          git add .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          commit-message: "docs: bump version to v${{ github.event.inputs.new_version }}"
          title: "docs: bump version to v${{ github.event.inputs.new_version }}"
          body: "Automated PR to bump versions."
          branch: "bump-version/v${{ github.event.inputs.new_version }}"
          delete-branch: true