name: chart-release

on:
  push:
    branches:
      - main
    paths:
      - '.version-chart'

permissions:
  contents: read
  packages: write

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release chart
    if: |
      ${{github.repository == 'robinlioret/gate-operator' && contains(github.event.head_commit.message, 'docs: bump chart versions to v')}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.1.0
        with:
          fetch-depth: 0

      - name: Extract version from .version-chart file
        id: extract_version
        run: |
          VERSION=$(cat .version-chart)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: 'v3.19.2'

      - name: Login to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm chart
        working-directory: ./dist/chart
        run: |
          helm package . \
            --app-version $(cat ../../.version) \
            --version $(cat ../../.version-chart)

      - name: Push Helm chart to GHCR
        working-directory: ./dist/chart
        run: |
          CHART_FILE="gate-operator-${{ steps.version.outputs.version }}.tgz"
          OCI_URL="oci://ghcr.io/${{ github.repository }}"
          
          echo "Pushing $CHART_FILE to $OCI_URL"
          helm push "$CHART_FILE" "$OCI_URL"